# SITE
url: 'https://piratesec.org'
baseurl: ''
permalink: /:categories/:title/

title: 'PirateSec'
subtitle: 'Pensacola State Cyber Defense Club'
description: 'Official website of the Pensacola State College Cyber Defense Club, home of PirateSec.'

# build
highlighter: rouge
exclude: ['js', 'node_modules', 'vendor', 'Gruntfile.js', 'package.json', 'package-lock.json', 'LICENSE', 'README.md']

# theme
featured-height: false # featured image height; options: intiger, default: false (300px)

# pixelate.js - class='pixelate', pixelateAll overides all settings
pixelate-featured: true # pixelate all header images; options: true, false, default: off false (off)
pixelate-all: false # pixelate all images; options: true, false, default: false (off)